name: AWS SAM [python3.8]
description: Run AWS SAM via GitHub Actions.|

             Heavily inspired by https://github.com/youyo/aws-sam-action
author: aksel <aksel@akseltorgard.com>
branding:
  icon: terminal
  color: yellow
inputs:
  sam_command:
    description: SAM subcommand to execute.
    required: true
  actions_comment:
    description: Whether or not to comment on pull requests.
    default: false
runs:
  using: docker
  image: ./Dockerfile
